Merge Launcher into Main app
maqsoftware/Pehla-School pull request #101
Opened 2019-06-28 05:01 UTC by agarg8487

|PR checklist|Status|
|-----|:------:|
|Is code analysis task executed and issues resolved in the Java/Kotlin code?|Yes|
|Is code analysis task executed and issues resolved in the CPP/native code?|NA|
|Is the version code set in the AndroidManifest.xml or build.gradle file to 1 more than the version which has already been published?|No|
|Is code commenting done properly for the changes made?|Yes|
|Is correct variable naming convention followed?|Yes|
|Is auto formatting shortcut Ctrl+Alt+Shift+L executed in all files?|Yes|
|Are the message strings used in the application taken from strings.xml file?|No|
|Are the permissions which are not required removed from AndroidManifest.java file?|NA|
|Is the _uses-feature_ tag used for only must have feature in AndroidManifest.java file?|NA|
|Are the generated files correctly configured in .gitignore?|Yes|
|Are the release signing configurations removed from the gradle files?|NA|
|Is commented code removed from all files?|Yes|
|Are updated images compressed (< 100 KB)?|NA|
|Ensured there are no typos in any string. For example: Variable/method names, hardcoded strings, commit messages, PR titles, issues, code comments?|Yes|

2019-07-05 04:56 UTC, harry6396 submitted a review, later dismissed

2019-07-05 06:44 UTC, ankitk20 requested changes

2019-07-05 06:44 UTC, ankitk20 commented on kitkitschoollogger/kitkitlogger/src/main/java/com/maq/kitkitlogger/KitKitLogger.java
>  //        } catch (PackageManager.NameNotFoundException e) {
Remove commented code

2019-07-05 06:44 UTC, ankitk20 commented on kitkitschoollogger/kitkitlogger/src/main/java/com/maq/kitkitProvider/User.java
> +        return true; /*this._finishTutorial;*/
Remove this

2019-07-05 06:44 UTC, ankitk20 commented on kitkitschoollogger/kitkitlogger/src/main/java/com/maq/kitkitlogger/KitKitLoggerActivity.java
>              //Context launcherContext = newBase.createPackageContext("todoschoollauncher.enuma.com.todoschoollauncher",0);
Remove this line

2019-07-05 06:44 UTC, ankitk20 commented on mainapp/proj.android-studio/app/build.gradle
> +    })
Remove test libs

2019-07-05 06:44 UTC, ankitk20 commented on mainapp/proj.android-studio/app/build.gradle
> +    compile 'com.android.support:design:25.1.0'
Upgrade this to 28.0.0

2019-07-05 06:44 UTC, ankitk20 commented on mainapp/proj.android-studio/app/src/org/cocos2dx/cpp/AppActivity.java
>                              Log.e(TAG, "", e);
Remove log

2019-07-05 06:44 UTC, ankitk20 commented on mainapp/proj.android-studio/app/src/org/cocos2dx/cpp/AppActivity.java
> +            Context launcherContext = createPackageContext("com.maq.xprize.kitkitschool.hindi", 0);
Use method to get package name.

2019-07-05 06:44 UTC, ankitk20 commented on mainapp/proj.android-studio/app/src/org/cocos2dx/cpp/ReadingBird/Recognizer.java
>                              if (mbCheckVolume == true) {
Do not use == true

2019-07-05 06:44 UTC, ankitk20 commented on mainapp/proj.android-studio/app/src/org/cocos2dx/cpp/ReadingBird/Recognizer.java
>                              if (mbCheckVolume == false) {
Do not use == false

2019-07-06 05:26 UTC, harry6396 approved these changes

2019-07-06 05:28 UTC, ankitk20 approved these changes

2019-07-06 05:33 UTC, mathewnik90 approved these changes

2019-07-06 05:34 UTC, merged