Merge Library into BookViewer app
maqsoftware/Pehla-School pull request #115
Opened 2019-07-03 06:50 UTC by agarg8487

|PR checklist|Status|
|-----|:------:|
|Is issue created in GitHub?|[Yes](https://github.com/maqsoftware/GLEXP-Team-KitkitSchool-Hindi/issues/103)|
|Is code analysis task executed and issues resolved in the Java/Kotlin code?|Yes|
|Is code analysis task executed and issues resolved in the CPP/native code?|NA|
|Is the version code set in the AndroidManifest.xml or build.gradle file to 1 more than the version which has already been published?|No|
|Is code commenting done properly for the changes made?|Yes|
|Is correct variable naming convention followed?|Yes|
|Is auto formatting shortcut Ctrl+Alt+Shift+L executed in all files?|Yes|
|Are the message strings used in the application taken from strings.xml file?|No|
|Are the permissions which are not required removed from AndroidManifest.java file?|NA|
|Is the _uses-feature_ tag used for only must have feature in AndroidManifest.java file?|NA|
|Are the generated files correctly configured in .gitignore?|Yes|
|Are the release signing configurations removed from the gradle files?|NA|
|Is commented code removed from all files?|Yes|
|Are updated images compressed (< 100 KB)?|NA|
|Ensured there are no typos in any string. For example: Variable/method names, hardcoded strings, commit messages, PR titles, issues, code comments?|Yes|

2019-07-04 04:43 UTC, ankitk20 requested changes

2019-07-04 04:43 UTC, ankitk20 commented on bookviewer/proj.android-studio/app/build.gradle
> +    })
Remove if not required

2019-07-04 04:43 UTC, ankitk20 commented on bookviewer/proj.android-studio/app/src/org/cocos2dx/cpp/BookApplication.java
> +            config.writeDebugLogs(); // Remove for release app
Remove == true

2019-07-04 07:44 UTC, agarg8487 commented on bookviewer/proj.android-studio/app/build.gradle
> +    })
Resolved.

2019-07-04 07:44 UTC, agarg8487 commented on bookviewer/proj.android-studio/app/src/org/cocos2dx/cpp/BookApplication.java
> +            config.writeDebugLogs(); // Remove for release app
Resolved.

2019-07-04 08:00 UTC, ankitk20 approved these changes

2019-07-04 09:10 UTC, harry6396 approved these changes

2019-07-05 05:36 UTC, mathewnik90 approved these changes

2019-07-05 05:53 UTC, mathewnik90 commented on bookviewer/proj.android-studio/app/src/org/cocos2dx/cpp/AppActivity.java
>              if (checkSelfPermission(android.Manifest.permission.READ_EXTERNAL_STORAGE)
Update the if condition to be negative, to avoid empty if statement

2019-07-05 06:16 UTC, merged