Fixed hindi number to english number word in number recognition of eg…
maqsoftware/Pehla-School pull request #143
Opened 2019-07-09 14:06 UTC by SanchitTaliyan

…gquiz

2019-07-09 14:25 UTC, SanchitTaliyan commented
|PR checklist|Status| 
|-----|:------:| 
|Is issue created in GitHub?[No] 
|Is code analysis task executed and issues resolved in the Java/Kotlin code?|Yes| 
|Is code analysis task executed and issues resolved in the CPP/native code?|Yes| 
|Is the version code set in the AndroidManifest.xml or build.gradle file to 1 more than the version which has already been published?|NA| 
|Is code commenting done properly for the changes made?|Yes| 
|Is correct variable naming convention followed?|Yes| 
|Is auto formatting shortcut Ctrl+Alt+Shift+L executed in all files?|Yes| 
|Are the message strings used in the application taken from strings.xml file?|No| 
|Are the permissions which are not required removed from AndroidManifest.java file?|NA| 
|Is the _uses-feature_ tag used for only must have feature in AndroidManifest.java file?|NA| 
|Are the generated files correctly configured in .gitignore?|Yes| 
|Are the release signing configurations removed from the gradle files?|NA| 
|Is commented code removed from all files?|Yes| 
|Are updated images compressed (< 100 KB)?|NA| 
|Ensured there are no typos in any string. For example: Variable/method names, hardcoded strings, commit messages, PR titles, issues, code comments?|Yes|

2019-07-09 15:10 UTC, ankitk20 requested changes

2019-07-09 15:10 UTC, ankitk20 commented on mainapp/Classes/Games/EggQuiz/EggQuizScene.cpp
> +    speaker->setFileName( convertToWords(TodoUtil::stoi(_problem.answer)));
Extra space before convertToWords

2019-07-09 15:10 UTC, ankitk20 commented on mainapp/Classes/Games/EggQuiz/EggQuizScene.cpp
> +    string numToWords(int n, string s)//Function used by convert to words
Use better var names

2019-07-09 15:10 UTC, ankitk20 commented on mainapp/Classes/Games/EggQuiz/EggQuizScene.cpp
> +    string one[] = { "", "one ", "two ", "three ", "four ",
Use a different name for this array

2019-07-09 15:10 UTC, ankitk20 commented on mainapp/Classes/Games/EggQuiz/EggQuizScene.cpp
> +        if (n)
Braces for if-else

2019-07-09 15:10 UTC, ankitk20 commented on mainapp/Classes/Games/EggQuiz/EggQuizScene.cpp
> +    string convertToWords(int n) //Function for convertToWords
Better var name

2019-07-09 15:10 UTC, ankitk20 commented on mainapp/Classes/Games/EggQuiz/EggQuizScene.cpp
> +        word += numToWords((n % 100), "");
Braces for if-else

2019-07-11 05:28 UTC, ankitk20 requested changes
Resolve comments

2019-07-11 06:03 UTC, ankitk20 requested changes

2019-07-11 06:03 UTC, ankitk20 commented on mainapp/Classes/Games/EggQuiz/EggQuizScene.cpp
>      {
Use a better name for s. Please do not use single letter names anywhere

2019-07-11 10:25 UTC, ankitk20 submitted a review, later dismissed

2019-07-11 11:08 UTC, mathewnik90 approved these changes

2019-07-11 11:08 UTC, merged