Removed unused permissions from the Manifest file
maqsoftware/Pehla-School pull request #30
Opened 2019-06-10 07:11 UTC by harry6396

2019-06-10 09:48 UTC, ankitk20 requested changes

2019-06-10 09:48 UTC, ankitk20 commented on launcher/app/src/main/AndroidManifest.xml
>                  <action android:name="android.intent.action.QUICKBOOT_POWERON" />
Check if this is also not required?

2019-06-10 09:48 UTC, ankitk20 commented on launcher/app/src/main/AndroidManifest.xml
>                  <action android:name="android.intent.action.ACTION_POWER_DISCONNECTED" />
Check these as well

2019-06-10 09:48 UTC, ankitk20 commented on library/app/src/main/AndroidManifest.xml
>                  <!--<category android:name="android.intent.category.LAUNCHER" />-->
Remove this

2019-06-10 09:48 UTC, ankitk20 commented on marimba/app/src/main/AndroidManifest.xml
>                  <!--<category android:name="android.intent.category.LAUNCHER" />-->
Remove this

2019-06-10 09:48 UTC, ankitk20 commented on seaworld/proj.android-studio/app/AndroidManifest.xml
>                  <!--<category android:name="android.intent.category.LAUNCHER" />-->
Remove this

2019-06-10 09:48 UTC, ankitk20 commented on writingboard/app/src/main/AndroidManifest.xml
>                  <!--<category android:name="android.intent.category.LAUNCHER" /> -->
Remove

2019-06-10 09:48 UTC, ankitk20 commented on mainapp/proj.android-studio/app/AndroidManifest.xml
>                  <!--<action android:name="android.intent.action.LAUNCHER" />-->
Remove

2019-06-11 07:34 UTC, harry6396 commented on writingboard/app/src/main/AndroidManifest.xml
>                  <!--<category android:name="android.intent.category.LAUNCHER" /> -->
Removed

2019-06-11 07:34 UTC, harry6396 commented on seaworld/proj.android-studio/app/AndroidManifest.xml
>                  <!--<category android:name="android.intent.category.LAUNCHER" />-->
Removed

2019-06-11 07:34 UTC, harry6396 commented on marimba/app/src/main/AndroidManifest.xml
>                  <!--<category android:name="android.intent.category.LAUNCHER" />-->
Removed

2019-06-11 07:35 UTC, harry6396 commented on library/app/src/main/AndroidManifest.xml
>                  <!--<category android:name="android.intent.category.LAUNCHER" />-->
Removed

2019-06-11 10:49 UTC, ankitk20 commented on bookviewer/proj.android-studio/app/debug/AndroidManifest.xml
> +    android:sharedUserId="com.maq.xprize.booktest">
Should **com.maq.kitkitschool.hindi** come here because that is the _sharedUserId_ you are using across. Am I right?

2019-06-11 10:54 UTC, ankitk20 submitted a review, later dismissed

2019-06-14 11:29 UTC, mathewnik90 submitted a review, later dismissed

2019-06-14 11:50 UTC, mathewnik90 approved these changes

2019-06-14 11:51 UTC, merged